&lt;?php include &#39;app/views/shares/header.php&#39;; ?&gt;
&lt;div class=&quot;container mt-5&quot;&gt;
    &lt;div class=&quot;row justify-content-center&quot;&gt;
        &lt;div class=&quot;col-lg-6&quot;&gt;
            &lt;div class=&quot;card shadow-sm&quot;&gt;
                &lt;div class=&quot;card-header bg-primary text-white&quot;&gt;
                    &lt;h3 class=&quot;mb-0&quot;&gt;Thêm Danh mục mới&lt;/h3&gt;
                &lt;/div&gt;
                &lt;div class=&quot;card-body&quot;&gt;
                    &lt;form action=&quot;/webbanhang/category/create&quot; method=&quot;POST&quot;&gt;
                        &lt;div class=&quot;mb-3&quot;&gt;
                            &lt;label for=&quot;name&quot; class=&quot;form-label fw-bold&quot;&gt;Tên Danh mục&lt;/label&gt;
                            &lt;input type=&quot;text&quot; class=&quot;form-control&quot; id=&quot;name&quot; name=&quot;name&quot; placeholder=&quot;Ví dụ: Điện thoại, Laptop...&quot; required&gt;
                        &lt;/div&gt;
                        &lt;div class=&quot;d-flex justify-content-end&quot;&gt;
                            &lt;a href=&quot;/webbanhang/category&quot; class=&quot;btn btn-secondary me-2&quot;&gt;Hủy&lt;/a&gt;
                            &lt;button type=&quot;submit&quot; class=&quot;btn btn-primary&quot;&gt;Lưu&lt;/button&gt;
                        &lt;/div&gt;
                    &lt;/form&gt;
                &lt;/div&gt;
            &lt;/div&gt;
        &lt;/div&gt;
    &lt;/div&gt;
&lt;/div&gt;
&lt;?php include &#39;app/views/shares/footer.php&#39;; ?&gt;